const mongoose = require("mongoose");

const FinalDataSchema = new mongoose.Schema({
    TranscriptID:Number,
    TranscriptContent:String,
    Agent_Name:String,
    Length:Number,
    Silence:Number,
    Overtalk:Number,
    AgentTalkTimee:Number,
    AgentWordCount:Number,
    ClientTalkTime:Number,
    ClientWordCount:Number,
    MonoTalkTime:Number,
    MonoWordCount:Number,
    diarization:String,
    Agent_diarized:String,
    Customer_diarized:String,
    Agent_Anger:Number,
    Agent_Sadness:Number,
    Agent_Excitement:Number,
    Agent_Satisfaction:Number,
    Agent_Empathy:Number,
    Agent_Friendliness:Number,
    Agent_Admiration:Number,
    Agent_Understanding:Number,
    Agent_Engagement:Number,
    Agent_Stress:Number,
    Agent_Confidence:Number,
    Agent_Professionalism:Number,
    Customer_Anger:Number,
    Customer_Sadness:Number,
    Customer_Excitement:Number,
    Customer_Satisfaction:Number,
    Customer_Empathy:Number,
    Customer_Friendliness:Number,
    Customer_Admiration:Number,
    Customer_Understanding:Number,
    Customer_Engagement:Number,
    Customer_Stress:Number,
    Customer_Confidence:Number,
    Customer_Professionalism:Number,
    summary:String,
    Top5Topics:[],
    AgentPerformanceReport:String, 
});

const FinalDataModel = mongoose.model("finaldatas", FinalDataSchema);

module.exports = FinalDataModel;
